- Learn Kyrillik
- Passpapiere (Was braucht man, wo liegt mein Reisepass, brauch ich das Teil?, ist der dann noch gültig)
- zweit Handy besorgen + SIM Karte
- irgendne körpernahe, wasserfeste Tasche mit Zeug was man brauch könnte wenns gen süden geht 
